### ISSUE TITLE
vite build fails on fresh install of framework

### ISSUE THREAD

**Issue by edalati** [laravel/vite-plugin#314]
### Vite Plugin Version

1.1.1

### Laravel Version

11.36.1

### Node Version

18.20.5

### NPM Version

10.8.2

### Operating System

Linux

### OS Version

Linux Mint 21.3 x86_64

### Web browser and version

Version 130.0.6723.116 (Official Build) for Linux Mint (64-bit)

### Running in Sail?

No

### Description

I have a fresh install of the framework after running `npm install` and then `npm run dev` i get this error:

`npm run dev

> dev
> vite

✘ [ERROR] Expected identifier but found "import"

    (define name):1:0:
      1 │ import.meta.dirname
        ╵ ~~~~~~

✘ [ERROR] Expected identifier but found "import"

    (define name):1:0:
      1 │ import.meta.filename
        ╵ ~~~~~~

✘ [ERROR] Expected identifier but found "import"

    (define name):1:0:
      1 │ import.meta.url
        ╵ ~~~~~~

failed to load config from /mnt/e/code/php/blocky/vite.config.js
error when starting dev server:
Error: Build failed with 3 errors:
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
    at failureErrorWithLog (/mnt/e/code/php/blocky/node_modules/esbuild/lib/main.js:1476:15)
    at /mnt/e/code/php/blocky/node_modules/esbuild/lib/main.js:945:25
    at runOnEndCallbacks (/mnt/e/code/php/blocky/node_modules/esbuild/lib/main.js:1316:45)
    at buildResponseToResult (/mnt/e/code/php/blocky/node_modules/esbuild/lib/main.js:943:7)
    at /mnt/e/code/php/blocky/node_modules/esbuild/lib/main.js:970:16
    at responseCallbacks.<computed> (/mnt/e/code/php/blocky/node_modules/esbuild/lib/main.js:622:9)
    at handleIncomingPacket (/mnt/e/code/php/blocky/node_modules/esbuild/lib/main.js:677:12)
    at Socket.readFromStdout (/mnt/e/code/php/blocky/node_modules/esbuild/lib/main.js:600:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
`

### Steps To Reproduce

composer create-project --prefer-dist laravel/laravel project
cd project
npm install
npm run dev

**Comment by edalati** [comment]
Related to this [https://github.com/vitejs/vite/issues/19018](https://github.com/vitejs/vite/issues/19018)
