### ISSUE TITLE
Config Loading Error When Using Environment Variables

### ISSUE THREAD

**Issue by cjmellor** [laravel/vite-plugin#45]
Hi,

I am trying to use an environment variable in the `vite.config.js` file. I have a variable `VITE_HOST` in my `.env` file and in `vite.config.js` I use `import.meta.env.VITE_HOST` as mentioned in the documentation.

When I run `yarn run dev` I get this output

```shell
❯ yarn run dev
yarn run v1.22.19
$ vite
failed to load config from /Users/chris.mellor/Dev/59club-platform/vite.config.js
error when starting dev server:
TypeError: Cannot read properties of undefined (reading 'VITE_HOST')
    at Object.<anonymous> (/Users/chris.mellor/Dev/59club-platform/vite.config.js:34:28)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at require.extensions.<computed> [as .js] (/Users/chris.mellor/Dev/59club-platform/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:61973:20)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfigFromBundledFile (/Users/chris.mellor/Dev/59club-platform/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:61981:17)
    at loadConfigFromFile (/Users/chris.mellor/Dev/59club-platform/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:61900:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It's the same with `npm` too.

Perhaps I am missing something?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by jessarcher** [comment]
@cjmellor `import.meta.env` is only available in files bundled by Vite. I.e. your application files.

In your `vite.config.js` file, you will want to use Node's `process.env`. E.g. `process.env.VITE_HOST`. You also don't strictly need the `VITE_` prefix in this file either, provided you have an env var called `HOST`.
