### ISSUE TITLE
vite.createFilter is not a function when use vue plugin in vite js config file

### ISSUE THREAD

**Issue by ahrasel** [laravel/vite-plugin#86]
- Laravel Vite Plugin Version: 0.4.0
- Laravel Version: 9.19
- Node Version: 16.15.0
- NPM Version: 8.5.5
- Host operating system:  Ubuntu

### Description:
```
yarn run v1.22.19
$ vite
failed to load config from /mnt/sdb1/htdocs/_client/sillage-clone/vite.config.ts
error when starting dev server:
TypeError: vite.createFilter is not a function
    at vuePlugin (/mnt/sdb1/htdocs/_client/sillage-clone/node_modules/@vitejs/plugin-vue/dist/index.cjs:2395:23)
    at Object.<anonymous> (/mnt/sdb1/htdocs/_client/sillage-clone/vite.config.ts:38:35)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.require.extensions.<computed> [as .ts] (/mnt/sdb1/htdocs/_client/sillage-clone/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:61998:20)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfigFromBundledFile (/mnt/sdb1/htdocs/_client/sillage-clone/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:62006:17)
    at loadConfigFromFile (/mnt/sdb1/htdocs/_client/sillage-clone/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:61925:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

![image](https://user-images.githubusercontent.com/12865001/179454498-39ca8947-1a9b-4220-9474-8208a2a81261.png)

**Comment by jessarcher** [comment]
I've never seen this error before - can you let me know what the following command returns:

`npm list | grep vite`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by jessarcher** [comment]
@ahrasel I'm pretty sure `@vitejs/plugin-vue` 3.x is for Vite 3. Try switching to the latest 2.x release of it.

Vite 3 support is coming very soon!
