### ISSUE TITLE
Laraver Forge error during deployment

### ISSUE THREAD

**Issue by Wit3** [laravel/vite-plugin#94]
- Laravel Vite Plugin Version: 0.5.0
- Laravel Version: 9.21.0
- Node Version: v12.22.1
- NPM Version: 6.14.12
- Host operating system:  Ubuntu 20.04

### Description:

package.json
```
    "devDependencies": {      
        "alpinejs": "^3.10.2",
        "axios": "^0.25",
        "laravel-vite-plugin": "^0.5.0",
        "lodash": "^4.17.19",
        "postcss": "^8.1.14",
        "postcss-import": "^14.0.1",
        "tailwindcss": "^3.1.4",
        "vite": "^3.0.2"
    },
```
During deployment in Laravel Forge

```
> vite build

file:///home/forge/nameofproject/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `vite build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jessarcher** [comment]
Hi @Wit3, could you please tell us what version of Node and NPM you are running on your Forge server?

**Comment by Wit3** [comment]
@jessarcher 

- Node Version: v12.22.1
- NPM Version: 6.14.12
